BEGIN TRANSACTION;
CREATE TABLE "milestones" (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`event`	INTEGER,
	`name`	TEXT,
	`pot`	NUMERIC DEFAULT 0,
	`achieved`	INTEGER DEFAULT 0
);
CREATE TABLE `events` (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`name`	TEXT
);
COMMIT;
